version: '3.7'

services:
  cms:
    image: cms
    build:
      context: build-cms
    privileged: true
    command: cms
    networks:
      - frontend
      - backend
    volumes:
      - ./config/cms.conf:/config/cms.conf
      - ./config/isolate.conf:/usr/local/etc/isolate
      - ./logs:/var/local/log/cms
      - ./cms:/cms
    restart: always
    depends_on:
      - cms_db
    environment:
      CMS_CONFIG: /config/cms.conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.${podName}.rule=Host(`${hostRule}`)
      - traefik.http.routers.${podName}.entrypoints=websecure
      - traefik.http.services.${podName}.loadbalancer.server.port=8888
      - traefik.http.routers.${podName}-admin.rule=Host(`${hostRule}`) && (`${hostRuleAdmin}`)
      - traefik.http.middlewares.${podName}-admin.stripprefix.prefixes=${hostRuleAdmin}
      - traefik.http.routers.${podName}-admin.entrypoints=websecure
      - traefik.http.services.${podName}-admin.loadbalancer.server.port=8889
      - traefik.docker.network=${podName}_frontend
    # Deploy block for docker swarm mode only - ignored by docker-compose
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  rws:
    image: cms:latest
    command: rws
    depends_on:
      - cms
    networks:
      - frontend
    volumes:
      - ./config/cms.ranking.conf:/usr/local/etc/cms.ranking.conf
      - ./logs:/var/local/log/cms
      - ./ranking:/var/local/lib/cms/ranking
      - ./cms:/cms
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.${podName}-rank.rule=Host(`${hostRule}`) && (`${hostRuleRank}`)
      - traefik.http.middlewares.${podName}-rank.stripprefix.prefixes=${hostRuleRank}
      - traefik.http.routers.${podName}-rank.entrypoints=websecure
      - traefik.http.services.${podName}-rank.loadbalancer.server.port=8890
      - traefik.docker.network=${podName}_frontend
    # Deploy block for docker swarm mode only - ignored by docker-compose
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  cms_db:
    image: postgres
    restart: always
    networks:
      - backend
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${dbName}
      POSTGRES_USER: ${dbUser}
      POSTGRES_PASSWORD: ${dbPass}
    # Deploy block for docker swarm mode only - ignored by docker-compose
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

networks:
  frontend:
  backend:
